---
title: Problem Set 6
author: Tobias Nowacki
output: pdf_document
urlcolor: blue
header-includes:
  - \usepackage{hayesmacros}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,          # don't show code
  warning = FALSE,       # don't show warnings
  message = FALSE,       # don't show messages (less serious warnings)
  cache = FALSE,         # set to TRUE to save results from last compilation
  fig.align = "center"   # center figures
)
library(tidyverse)
library(MASS)
library(broom)
library(kableExtra)
library(boot)
library(mlogit)
library(nnet)
library(rio)
library(sandwich)
library(lmtest)
library(gridExtra)
library(Zelig)
library(stargazer)
library(mgcv)
library(factoextra)

theme_sv <- function(){ # Custom ggplot theme
  theme_bw(base_size=11) %+replace%
  theme(
    panel.grid.major =  element_line(
      colour = "grey50",
      size = 0.2,
      linetype = "dotted"),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = "grey97"),
    plot.margin 	 = unit(c(0.2, 1, 0.2, 1), "cm"),
    legend.margin 	 = margin(0, 0, 0, 0),
    legend.title  	 = element_text(size = 10, face = "bold"),
    strip.background = element_rect(fill= NULL,
                                    colour = "white", 
                                    linetype = NULL),
    strip.text 		 = element_text(colour = 'grey50', 
                                 	size = 9, 
                                 	vjust = 0.5)
  )
}

options(device = function(file, width = 7, height = 7, ...) {
  cairo_pdf(tempfile(), width = width, height = height, ...)
})
                         # with code you use a lot and loading it here as well
set.seed(27)             # make random results reproducible
```

```{r}
df1 <- import("hw6data/hw6_q1.csv")

mod3 <- glm(exile ~ culpable + maxintyear + domestic7 + tenure + idealpoint + gwf_dem + post1998 + post1998 * culpable, data = df1, family = binomial())
mod3se <- sqrt(diag(vcovCL(mod3, cluster = df1$leader)))

mod3 <- glm(exile ~ culpable + maxintyear + domestic7 + tenure + idealpoint + gwf_dem + post1998 + post1998 * culpable, data = df1, family = binomial())
mod3vcov <- vcovCL(mod3, cluster = df1$leader)
mod3se <- sqrt(diag(mod3vcov))

coef3_sum <- mod3$coef[2] + mod3$coef[9]
coef3_sum_se <- sqrt(mod3vcov[2, 2] + mod3vcov[9, 9] + 2 * mod3vcov[2, 9])
print(c(coef3_sum, coef3_sum_se))
```

```{r}
df1$idealbin <- cut(df1$idealpoint, breaks =  c(-1000, -0.66, 0.82, 1000), labels = 1:3)

mod4 <- glm(exile ~ culpable + maxintyear + domestic7 + tenure + as.factor(idealbin) + gwf_dem + post1998 + post1998 * culpable, data = df1, family = binomial())
mod4vcov <- vcovCL(mod4, cluster = df1$l\textbf{}eader)
mod4se <- sqrt(diag(vcovCL(mod4, cluster = df1$leader)))

coef4_sum <- mod4$coef[2] + mod4$coef[9]
coef4_sum_se <- sqrt(mod4vcov[2, 2] + mod4vcov[9, 9] + 2 * mod4vcov[2, 9])
print(c(coef4_sum, coef4_sum_se))

stargazer(mod3, mod4, se = list(mod3se, mod4se))
```


```{r ref.label = knitr::all_labels(), echo = TRUE, eval = FALSE}
# this R markdown chunk generates a code appendix
```

